spring.application.name=be-api

spring.datasource.url=jdbc:postgresql://db.fcrqkbvbrkvmdsvlvden.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=zHZruvXxPCbmdEWs
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8082

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG