spring.application.name=be-api


# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.fcrqkbvbrkvmdsvlvden&password=zHZruvXxPCbmdEWs
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
server.port=8080

logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN
logging.level.org.springframework.jdbc.support=WARN

# Jackson date/time format
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.time-zone=Asia/Ho_Chi_Minh

# Supabase Configuration
supabase.jwt.secret=${SPB_JWT_SECRET_KEY}
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheQueries=0